config/routes.rb
Orwapp::Application.routes.draw do

  resources :languages
  resources :professions
  ActiveAdmin.routes(self)
  resources :submissions
  resources :dynamic_forms do
    get :submissions
  end


  namespace :inventories do
    post :search
  end

  resources :locations
  resources :skills
  resources :inventories
  resources :departments
  resources :attachments

  devise_for :users

  mount API => '/'

  get '/daily_report/:project_id/:profession_id/:overtime' => 'excel#daily_report',
    as: :daily_report

  get 'monthly_report/:project_id/:year/:month/:overtime' => 'excel#monthly_report',
      as: :monthly_report

  resources :projects do
    post :approve_hours
    get :billable_hours
    get :personal_hours
    get :hours
    get :documentation
    get :deviation
    resources :tasks, :controller => 'projects/tasks' do
      put :end_task
      put :end_task_hard
      get :tools
      get :workers
      get :review
    end

    resources :project_reports, only: :create
    member do
      post :complete
    end
  end
  resources :project_reports, only: :show

  get '/timesheets' => 'excel#timesheets', as: :timesheets
  get '/timesheet/:project_id/:user_id' => 'excel#timesheet', as: :timesheet

  namespace :excel do
  end

  namespace :tasks do
    get :active
    get :report
    get :qualified_workers
    post :select_inventory, as: :select_inventory
    post :select_workers,   as: :select_workers
    get :selected_workers,  as: :selected_workers
    get :selected_inventories
    get :inventories
    delete :remove_selected_worker
    delete :remove_selected_inventory
  end

  get '/customers/search' => 'customers#search', as: :customer_search
  resources :customers do
    resources :projects, :controller => 'customers/projects'
    get :excel_report
  end

  get '/users/search/'=> 'users#search', as: :user_search

  resources :users do
    resources :user_languages
    resources :kids
    get '/tasks/started'     => 'users/tasks#started'
    get '/tasks/not_started' => 'users/tasks#not_started'
    get '/projects/:project_id/hours'=> 'users#hours', as: :hours
    post '/projects/:project_id/hours'=> 'users#hours', as: :approve_hours
    get :timesheets
    get :certificates
    patch '/create_certificate/' => 'users#create_certificate', as: :create_certificate
    resources :certificates, :controller => 'users/certificates', only: [:show, :destroy]
    resources :tasks, :controller => 'users/tasks' do
      post :accept_task
      post :finished
      get :send_message
    end
    resources :tasks, :controller => 'users/user_tasks' do
      post :confirm_user_task
    end
    collection do
      post :add_user
    end
  end
  resources :certificates

  resources :hours_spents do
  end
  resources :tasks do
    post :save_and_order_resources,   as: :save_and_order_resources
    resources :hours_spents, :controller => 'tasks/hours_spents' do
      get  :approve
    end
    member do
      post :complete
    end
  end


  get '/blog'             => 'blog#index',            as: :blog
  get '/news_archive'     => 'blog#news_archive',     as: :news_archive
  get '/projects_archive' => 'blog#projects_archive', as: :projects_archive
  get '/hms'              => 'blog#hms',              as: :hms
  get '/instructions'     => 'blog#instructions',     as: :instructions
  get '/video'            => 'blog#video',            as: :video
  get '/video/:id'        => 'blog#video',            as: :current_video
  get '/administration'   => 'blog#administration',   as: :administration
  get '/hr'               => 'blog#hr',               as: :hr


  get '/manager' => 'blog#frontpage_manager', as: :frontpage_manager
  get '/worker'  => 'blog#frontpage_user', as: :frontpage_user
  get '/new_assignment' => 'blog#new_assignment', as: :new_assignment
  get '/sallery/:user_id/:project_id/'  => 'excel#sallery', as: :sallery_report
  get '/blog/:content_type/:id' => 'blog#content', as: :blog_content


  get '/html_export/:user_id/:project_id/' => 'excel#html_export', as: :html_export

  get '/templates/:path' => 'templates#template',
    :constraints => { :path => /.+/  }

  get '/hse' => 'hse#redirect', as: 'hse'

  post '/blog_images' => 'blog_images#create', as: :blog_images

  #get '*path' => redirect('/')
  root 'blog#index'
end

app/models/kid.rb
# == Schema Information
#
# Table name: kids
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  name         :string
#  birth_date   :date
#  sole_custody :boolean          default(FALSE)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Kid < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true
  validates :user, presence: true
  validates :birth_date, presence: true

  def age
    now = Time.now.utc.to_date
    now.year - birth_date.year - (birth_date.to_date.change(:year => now.year) > now ? 1 : 0)
  end

end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  before_action :set_kid, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:index, :new, :create, :show,
                                  :edit, :update, :destroy]

  # GET /kids
  # GET /kids.json
  def index
    @kids = Kid.all
  end

  # GET /kids/1
  # GET /kids/1.json
  def show
  end

  # GET /kids/new
  def new
    @kid = Kid.new
  end

  # GET /kids/1/edit
  def edit
  end

  # POST /kids
  # POST /kids.json
  def create
    @kid = Kid.new(kid_params)
    @kid.user = @user

    respond_to do |format|
      if @kid.save
        format.html { redirect_to user_kids_path(@user), notice: 'Barnet er lagret' }
        format.json { render action: 'show', status: :created, location: @kid }
      else
        format.html { render action: 'new' }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kids/1
  # PATCH/PUT /kids/1.json
  def update
    respond_to do |format|
      if @kid.update(kid_params)
        format.html { redirect_to user_kids_path(@user), notice: t(:saved) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kids/1
  # DELETE /kids/1.json
  def destroy
    @kid.destroy
    respond_to do |format|
      format.html { redirect_to user_kids_path(@user), notice: 'Slettet' }
      format.json { head :no_content }
    end
  end

  private
    def set_kid
      @kid = Kid.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    def kid_params
      params.require(:kid).permit(:references, :name, :birth_date, :sole_custody)
    end
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/views/kids/_form.html.slim
= form_for [@user, @kid] do |f|
  = render partial: 'layouts/form_error_messages', locals: { form_object: @kid }

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :birth_date
    = f.date_select(:birth_date, start_year: 1983)
  .checkbox
    label
      = f.check_box :sole_custody
      = t(:sole_custody)

  .actions = f.submit t(:save)

app/views/kids/edit.html.slim
h1 Rediger

== render 'form'

= link_to t(:back), user_kids_path(@kid.user)

app/views/kids/index.html.slim
- content_for :breadcrumb do
  = link_to t('top_nav.manage'), administration_path
  = fa_icon 'chevron-right'
  = link_to t('admin.users'),        users_path
  = fa_icon 'chevron-right'
  = link_to @user.name, edit_user_path(@user)
  = fa_icon 'chevron-right'
  strong Barn

h1= "Barna til #{@user.name}"
br
br

table
  thead
    tr
      th Navn
      th Fødselsdato / Alder
      th Eneomsorg
      th
      th

  tbody
    - @kids.each do |kid|
      tr
        td = kid.name
        td = "#{l kid.birth_date} / #{kid.age}"
        td = kid.sole_custody ? 'Ja' : 'Nei'
        td = link_to t(:edit), edit_user_kid_path(@user, kid)
        td = link_to t(:destroy), user_kid_path(@user, kid),
          data: {:confirm => 'Slette?'}, :method => :delete

br

= link_to 'Legg til et barn', new_user_kid_path, class: 'btn btn-primary'
br
= link_to "Tilbake", edit_user_path(@user)

app/views/kids/new.html.slim
h1 Registrer et nytt barn

== render 'form'

= link_to t(:back), user_kids_path(@user)

app/views/kids/show.html.slim
p#notice = notice

p
  strong Name:
  = @kid.name
p
  strong Fødselsdato / Alder:
  = "#{@kid.birth_date} / #{@kid.age}"
p
  strong Sole custody:
  = @kid.sole_custody

= link_to 'Edit', edit_kid_path(@kid)
'|
= link_to 'Back', kids_path