config/routes.rb
Orwapp::Application.routes.draw do

  resources :languages
  resources :professions
  ActiveAdmin.routes(self)
  resources :submissions
  resources :dynamic_forms do
    get :submissions
  end


  namespace :inventories do
    post :search
  end

  resources :locations
  resources :skills
  resources :inventories
  resources :departments
  resources :attachments

  devise_for :users

  mount API => '/'

  get '/daily_report/:project_id/:profession_id/:overtime' => 'excel#daily_report',
    as: :daily_report

  get 'monthly_report/:project_id/:year/:month/:overtime' => 'excel#monthly_report',
      as: :monthly_report

  resources :projects do
    post :approve_hours
    get :billable_hours
    get :personal_hours
    get :hours
    get :documentation
    get :deviation
    resources :tasks, :controller => 'projects/tasks' do
      put :end_task
      put :end_task_hard
      get :tools
      get :workers
      get :review
    end

    resources :project_reports, only: :create
    member do
      post :complete
    end
  end
  resources :project_reports, only: :show

  get '/timesheets' => 'excel#timesheets', as: :timesheets
  get '/timesheet/:project_id/:user_id' => 'excel#timesheet', as: :timesheet

  namespace :excel do
  end

  namespace :tasks do
    get :active
    get :report
    get :qualified_workers
    post :select_inventory, as: :select_inventory
    post :select_workers,   as: :select_workers
    get :selected_workers,  as: :selected_workers
    get :selected_inventories
    get :inventories
    delete :remove_selected_worker
    delete :remove_selected_inventory
  end

  get '/customers/search' => 'customers#search', as: :customer_search
  resources :customers do
    resources :projects, :controller => 'customers/projects'
    get :excel_report
  end

  get '/users/search/'=> 'users#search', as: :user_search

  resources :users do
    resources :user_languages
    resources :kids
    get '/tasks/started'     => 'users/tasks#started'
    get '/tasks/not_started' => 'users/tasks#not_started'
    get '/projects/:project_id/hours'=> 'users#hours', as: :hours
    post '/projects/:project_id/hours'=> 'users#hours', as: :approve_hours
    get :timesheets
    get :certificates
    patch '/create_certificate/' => 'users#create_certificate', as: :create_certificate
    resources :certificates, :controller => 'users/certificates', only: [:show, :destroy]
    resources :tasks, :controller => 'users/tasks' do
      post :accept_task
      post :finished
      get :send_message
    end
    resources :tasks, :controller => 'users/user_tasks' do
      post :confirm_user_task
    end
    collection do
      post :add_user
    end
  end
  resources :certificates

  resources :hours_spents do
  end
  resources :tasks do
    post :save_and_order_resources,   as: :save_and_order_resources
    resources :hours_spents, :controller => 'tasks/hours_spents' do
      get  :approve
    end
    member do
      post :complete
    end
  end


  get '/blog'             => 'blog#index',            as: :blog
  get '/news_archive'     => 'blog#news_archive',     as: :news_archive
  get '/projects_archive' => 'blog#projects_archive', as: :projects_archive
  get '/hms'              => 'blog#hms',              as: :hms
  get '/instructions'     => 'blog#instructions',     as: :instructions
  get '/video'            => 'blog#video',            as: :video
  get '/video/:id'        => 'blog#video',            as: :current_video
  get '/administration'   => 'blog#administration',   as: :administration
  get '/hr'               => 'blog#hr',               as: :hr


  get '/manager' => 'blog#frontpage_manager', as: :frontpage_manager
  get '/worker'  => 'blog#frontpage_user', as: :frontpage_user
  get '/new_assignment' => 'blog#new_assignment', as: :new_assignment
  get '/sallery/:user_id/:project_id/'  => 'excel#sallery', as: :sallery_report
  get '/blog/:content_type/:id' => 'blog#content', as: :blog_content


  get '/html_export/:user_id/:project_id/' => 'excel#html_export', as: :html_export

  get '/templates/:path' => 'templates#template',
    :constraints => { :path => /.+/  }

  get '/hse' => 'hse#redirect', as: 'hse'

  post '/blog_images' => 'blog_images#create', as: :blog_images

  #get '*path' => redirect('/')
  root 'blog#index'
end

app/controllers/api/v1/customers_controller.rb
module Api
  module V1
    class CustomersController < ApplicationController
      before_action :set_customer, only: [:show, :edit, :update, :destroy]
      skip_before_filter :verify_authentication_token
      respond_to :json

      # GET /customers
      # GET /customers.json
      def index
        respond_with(Customer.all.to_a)
      end

      # GET /customers/1
      # GET /customers/1.json
      def show
      end

      # GET /customers/new
      def new
        @customer = Customer.new
      end

      # GET /customers/1/edit
      def edit
      end


      # POST /customers
      # POST /customers.json
      def create
        @customer = Customer.new(customer_params)

        respond_to do |format|
          if @customer.save!
            format.html { redirect_to @customer, 
                          notice: I18n.t('saved') }
            format.json { render action: 'show', 
                          status: :created, location: @customer }
          else
            format.html { render action: 'new' }
            format.json { render json: @customer.errors, 
                          status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /customers/1
      # PATCH/PUT /customers/1.json
      def update
        respond_to do |format|
          if @customer.update(customer_params)
            format.html { redirect_to @customer, 
                          notice: 'Customer was successfully updated.' }
            format.json { head :no_content }
          else
            format.html { render action: 'edit' }
            format.json { render json: @customer.errors, 
                          status: :unprocessable_entity }
          end
        end
      end

      # DELETE /customers/1
      # DELETE /customers/1.json
      def destroy
        @customer.destroy
        respond_to do |format|
          format.html { redirect_to customers_url }
          format.json { head :no_content }
        end
      end

      private
      # Use callbacks to share common setup or constraints between actions.
      def set_customer
        @customer = Customer.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def customer_params
        params.require(:customer).permit(:name, :address, :org_number, 
                                         :contact_person, :phone)
      end
    end
  end
end

app/controllers/api/v1/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.active.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, 
                      notice: t('saved') }
        format.json { render action: 'show', status: :created, 
                      location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, 
                      status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, 
                      notice: t('updated') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, 
                      status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:project_number, 
                                      :name, 
                                      :customer_id,
                                      :start_date,
                                      :due_date,
                                      :hour_rate,
                                      :fixed_price, :description,
                                      :price_total,
                                      :company_id)
    end
end

app/controllers/customers/projects_controller.rb
class Customers::ProjectsController < ApplicationController
  before_action :set_project,  only: [:show, :edit, :update, :destroy]
  before_action :set_customer, only: [:index, :show, :edit, :update,
                                      :destroy, :new]


  def index
    @projects = @customer.projects.active.all
  end

  def show
    @departments       = Department.all
    @drafts            = @project.task_drafts
    @tasks_in_progress = @project.tasks_in_progress
    @completed_tasks   = @project.completed_tasks
  end

  def new
    @project     = @customer.projects.new
    @customers   = Customer.all
    @departments = Department.all
  end

  def edit
    @departments = Department.all
    @is_favorite = @project.is_favorite_of?(@current_user)
  end

  def create
    @project      = Project.new(project_params)
    @project.user = @current_user
    @departments  = Department.all

    @project.customer_id = params[:customer_id] if params[:customer_id].present?
    @customers           = Customer.all
    @customer            = Customer.find(params[:customer_id])

    if @project.single_task? && @project.valid?
      @task = @project.build_single_task
    end

    respond_to do |format|
      if @project.save
        set_favorite
        if params[:attachments]
          params[:attachments].each_with_index do |attachment, i|
            @project.attachments.create!(document: attachment,
                                         description: params[:att_descriptions][i],
                                         project: @project)
          end
        end

        format.html do
          if @project.single_task?
            redirect_to edit_project_task_path(@project, @task),
              notice: 'Prosjektet ble lagret'
          else
            redirect_to customer_project_path(@project.customer,
                                              @project),
                                              notice: 'Prosjektet ble lagret'
          end
        end
        format.json { render action: 'show', status: :created,
                      location: @project }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors,
                      status: :unprocessable_entity }
      end
    end
  end

  def update
    @departments = Department.all
    respond_to do |format|
      if @project.update(project_params)
        set_favorite
        if params[:attachments]
          params[:attachments].each_with_index do |attachment, i|
            @project.attachments.create!(document: attachment,
                                         description: params[:att_descriptions][i])
          end
        end

        format.html { redirect_to [@project.customer, @project],
                      notice: t('updated') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors,
                      status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  def set_customer
    @customer = Customer.find(params[:customer_id])
  end

  def set_favorite
    if params[:starred]
      @current_user.favorites << @project.set_as_favorite
    else
      @project.unset_favorite(@current_user)
    end
  end

  def project_params
    params.require(:project).permit(
                                    :attachments,
                                    :billing_address,
                                    :customer_reference,
                                    :company_id,
                                    :comment,
                                    :customer_id,
                                    :due_date,
                                    :description,
                                    :department_id,
                                    :delivery_address,
                                    :execution_address,
                                    :name,
                                    :project_number,
                                    :sms_employee_if_hours_not_registered,
                                    :sms_employee_when_new_task_created,
                                    :start_date,
                                    :title,
                                    :single_task
                                    )
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  before_action :redirect_if_not_project_leader

  # GET /customers
  # GET /customers.json
  def index
    @search    = Customer.search(params[:q])
    @search.sorts = 'name asc' if @search.sorts.empty?
    @customers = @search.result
    paginate_customers(@customers)
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
    @is_favorite = @customer.is_favorite_of?(@current_user)
  end

  def search
    @customers = Customer.where("name ILIKE ?", "%#{params[:query]}%").all
    @search    = Customer.search(params[:q])
    @show_all = true
    render :index
  end


  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        set_favorite
        format.html { redirect_to @customer,
                      notice: I18n.t('saved') }
        format.json { render action: 'show',
                      status: :created, location: @customer }
      else
        format.html { render action: 'new' }
        format.json { render json: @customer.errors,
                      status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        set_favorite
        format.html { redirect_to @customer,
                      notice: I18n.t('updated') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @customer.errors,
                      status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet,
    # only allow the white list through.
    def customer_params
      params.require(:customer).permit(
        :name,
        :email,
        :address,
        :org_number,
        :contact_person,
        :phone)
    end

    def set_favorite
      if params[:starred]
        @current_user.favorites << @customer.set_as_favorite
      else
        @customer.unset_favorite(@current_user)
      end
    end

    def redirect_if_not_project_leader
      redirect_to root_url,
        notice: 'Only for project leaders' unless @current_user.is? 'project_leader'
    end

    def paginate_customers(customers, query = '')
      return if customers.empty?
      alpha_paginate_options = {
          :support_language => :en,
          :pagination_class => 'pagination-centered',
          :js => false,
          :include_all => false,
          :query => query,
          :default_field => get_paginate_default_field(
                                customers.order(:name).first.name[0])
      }
      @customers, @alpha_params = customers.alpha_paginate(
                                    params[:letter],
                                    alpha_paginate_options) { |c| c.name }
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper


  def project_number(p)
    p.project_number.present? ? p.project_number : "Prosjekt ##{p.id}"
  end

end

app/views/customers/projects/_form.html.slim
== form_for [@customer, @project], :html => { :multipart => true }  do |f|
  - if @project.errors.any?
    #error_explanation
      h2
        = "#{@project.errors.count} feil"
        =   " hindret prosjektet fra å bli lagret "
      ul
        - @project.errors.full_messages.each do |message|
          li = message

  .field.right
    .checkbox
      label
        = check_box_tag :starred, @is_favorite ? 1 : 0, @is_favorite
        | Merk som favoritt

  .field
    = f.label :department, 'Avdeling'
    = select_tag "project[department_id]",
      options_from_collection_for_select(@departments, "id",
        "title", (@project.department_id || @current_user.department.id))



  .field
    = f.label :project_number
    = f.text_field :project_number

  .field
    = f.label :name
    = f.text_field :name

  .field
    = f.label :description
    = f.text_area :description, rows: 5

  .field
    = f.label :customer_reference
    = f.text_field :customer_reference, value: @project.customer_reference

  .field
    = f.label :comment
    = f.text_area :comment, value: @project.comment

  .field
    h3 Dato
    = f.label :start_date
    = f.text_field :start_date, class: :datepicker, placeholder: 'Velg dato'

  .field
    = f.label :due_date
    = f.text_field :due_date, class: :datepicker,  placeholder: 'Velg dato'

  hr

  .field.radio_group
    h3 = Project.human_attribute_name("execution_address")
    = f.text_area :execution_address, value: @project.address


  .field
    h3 = I18n.t('notifications')
    .checkbox
      label
        = f.check_box :sms_employee_if_hours_not_registered
        = 'Send SMS til ansatt som ikke har ført timer kl 17 samme dag'
    .checkbox
      label
        = f.check_box :sms_employee_when_new_task_created
        = 'Send SMS til ansatt når han får tildelt ny oppgave'


  br
  hr
  .project-attachments
    .field
      = f.label :attachment, 'Velg vedlegg'
      = file_field_tag "attachments[]", type: :file, multiple: true, id: nil
      = text_field_tag "att_descriptions[]", nil, placeholder: 'Filbeskrivelse', id: nil

    button.plus-button type='button' +
  hr

  .field.single-task
    .checkbox
      label for='project_single_task'
        = f.check_box :single_task
        = t('.single_task')

  hr

  .actions = f.submit t('save')

app/views/customers/projects/_info.html.slim
.box-shadow
  - unless @project.default
    p
      strong= t('project_owner')
      br
      = @project.user.full_name rescue '-'
  p
    strong = t('name')
    br
    = @project.name

  - unless @project.default
    p
      strong = t('project_number')
      br
      = @project.project_number
    p
      strong = t('address')
      br
      = @project.address
    p
      strong = t('customer')
      br
      = @project.customer.name

  strong = t('description')
  = simple_format @project.description

  - unless @project.default
    p
      strong= 'Oppstart'
      br
      = I18n.l(@project.start_date, format: :short_w_year) rescue nil
    p
      strong= 'Ferdigstilling'
      br
      = I18n.l(@project.due_date, format: :short_w_year) rescue '-'

  - if @project.attachments.exists?
    strong Vedlegg
    br
    - @project.attachments.each do |a|
      = a.description
      br
      = link_to a.document.url, a.document.url
      br

  .right
    = link_to t('edit'), edit_customer_project_path(@project.customer, @project)
  br

app/views/customers/projects/_task.html.slim
/= render '/tasks/show.html.slim'
.button.green
  table
    thead
      th Kunde
      th Utførende
      th Type oppdrag
    tbody
      tr
        td = task.customer.name

  
br
br
= link_to 'Rediger ', edit_task_path(task)
'|
= link_to 'Tilbake', :back, class: 'button primary'

app/views/customers/projects/edit.html.slim
h1 Rediger prosjekt

br
== render 'form'

br
= link_to 'Tilbake', projects_path

app/views/customers/projects/index.html.slim
h1= "Prosjekter under #{link_to @customer.name, customer_path(@customer)}".html_safe

= render partial: "projects/table", locals: {projects: @projects} 

app/views/customers/projects/new.html.slim
- content_for :breadcrumb do
  = link_to 'Mine prosjekter', projects_path
  = fa_icon 'chevron-right'
  = link_to @project.customer.name, customer_path(@project.customer)
  = fa_icon 'chevron-right'
  strong= 'Lag nytt prosjekt'

h1=  "Lag et nytt projekt under #{@project.customer.name}"
br

== render 'form'

= link_to 'Tilbake', projects_path

app/views/customers/projects/report.html.slim
- @week_nr = Time.now.strftime("%U").to_i

h2= "Timerapport uke #{@week_nr}"
br
br


- @customers.each do |c|
  - next if c.tasks.blank?

  .button.green
    h1.right= fa_icon 'print'
    h2 = "#{c.name}"
    - c.tasks.all.each do |t|
      hr
      ul.hour_report
        li
          strong= "Hvem: "
          span=  "#{t.user.name}"
          br
          - if t.description.present?
            strong= "Hva: "
            span= "#{t.description}"
            br

          - t.hours_spents.each do |h|
            p
              strong= "Dato: "
              span= "#{h.date}"
              br

              strong= "Beskrivelse: "
              span= "#{h.description}"

              br
              strong= "Antall timer: "
              span= "#{h.hour}"
          hr
          strong= "Totalt timer: "
          span= "#{t.hours_spents.sum(:hour)}"
  .button.primary
    span= "Timer totalt ført på #{c.name} i uke #{@week_nr}: <strong>#{rand(200..450)}</strong>".html_safe
  = link_to 'Dagsrapport', customer_excel_report_path(c)
  br
  br
  br

h1.right= fa_icon 'print'

= link_to "Tilbake", frontpage_manager_path, class: 'secondary_button'
br
br
br

app/views/customers/projects/show.html.slim
- content_for :breadcrumb do
  = link_to t('my_projects'), projects_path
  = fa_icon 'chevron-right'
  = link_to @project.customer.name, customer_path(@project.customer)
  = fa_icon 'chevron-right'
  strong= @project.name

#project-action-buttons.btn-group(role="group")
  = link_to t('show_hours_registered'), project_hours_path(@project),
    class: "btn btn-primary"
  = link_to t('register_new_task'), new_project_task_path(@project),
    class: "btn btn-primary"
  = link_to 'Prosjektdokumentasjon', project_documentation_path(@project),
    class: "btn btn-primary"
  - unless @project.complete
    = link_to t('projects.complete_link'), complete_project_path(@project),
        data: { confirm: t('generic.confirm') }, method: :post,
        class: 'complete btn btn-primary'

.badges
  - if @project.complete
    span.badge.success = t('complete')

= render 'info'
br
br
= render 'tasks'
br
br
br
= link_to t('back'), @project.customer