config/routes.rb
Orwapp::Application.routes.draw do

  resources :languages
  resources :professions
  ActiveAdmin.routes(self)
  resources :submissions
  resources :dynamic_forms do
    get :submissions
  end


  namespace :inventories do
    post :search
  end

  resources :locations
  resources :skills
  resources :inventories
  resources :departments
  resources :attachments

  devise_for :users

  mount API => '/'

  get '/daily_report/:project_id/:profession_id/:overtime' => 'excel#daily_report',
    as: :daily_report

  get 'monthly_report/:project_id/:year/:month/:overtime' => 'excel#monthly_report',
      as: :monthly_report

  resources :projects do
    post :approve_hours
    get :billable_hours
    get :personal_hours
    get :hours
    get :documentation
    get :deviation
    resources :tasks, :controller => 'projects/tasks' do
      put :end_task
      put :end_task_hard
      get :tools
      get :workers
      get :review
    end

    resources :project_reports, only: :create
    member do
      post :complete
    end
  end
  resources :project_reports, only: :show

  get '/timesheets' => 'excel#timesheets', as: :timesheets
  get '/timesheet/:project_id/:user_id' => 'excel#timesheet', as: :timesheet

  namespace :excel do
  end

  namespace :tasks do
    get :active
    get :report
    get :qualified_workers
    post :select_inventory, as: :select_inventory
    post :select_workers,   as: :select_workers
    get :selected_workers,  as: :selected_workers
    get :selected_inventories
    get :inventories
    delete :remove_selected_worker
    delete :remove_selected_inventory
  end

  get '/customers/search' => 'customers#search', as: :customer_search
  resources :customers do
    resources :projects, :controller => 'customers/projects'
    get :excel_report
  end

  get '/users/search/'=> 'users#search', as: :user_search

  resources :users do
    resources :user_languages
    resources :kids
    get '/tasks/started'     => 'users/tasks#started'
    get '/tasks/not_started' => 'users/tasks#not_started'
    get '/projects/:project_id/hours'=> 'users#hours', as: :hours
    post '/projects/:project_id/hours'=> 'users#hours', as: :approve_hours
    get :timesheets
    get :certificates
    patch '/create_certificate/' => 'users#create_certificate', as: :create_certificate
    resources :certificates, :controller => 'users/certificates', only: [:show, :destroy]
    resources :tasks, :controller => 'users/tasks' do
      post :accept_task
      post :finished
      get :send_message
    end
    resources :tasks, :controller => 'users/user_tasks' do
      post :confirm_user_task
    end
    collection do
      post :add_user
    end
  end
  resources :certificates

  resources :hours_spents do
  end
  resources :tasks do
    post :save_and_order_resources,   as: :save_and_order_resources
    resources :hours_spents, :controller => 'tasks/hours_spents' do
      get  :approve
    end
    member do
      post :complete
    end
  end


  get '/blog'             => 'blog#index',            as: :blog
  get '/news_archive'     => 'blog#news_archive',     as: :news_archive
  get '/projects_archive' => 'blog#projects_archive', as: :projects_archive
  get '/hms'              => 'blog#hms',              as: :hms
  get '/instructions'     => 'blog#instructions',     as: :instructions
  get '/video'            => 'blog#video',            as: :video
  get '/video/:id'        => 'blog#video',            as: :current_video
  get '/administration'   => 'blog#administration',   as: :administration
  get '/hr'               => 'blog#hr',               as: :hr


  get '/manager' => 'blog#frontpage_manager', as: :frontpage_manager
  get '/worker'  => 'blog#frontpage_user', as: :frontpage_user
  get '/new_assignment' => 'blog#new_assignment', as: :new_assignment
  get '/sallery/:user_id/:project_id/'  => 'excel#sallery', as: :sallery_report
  get '/blog/:content_type/:id' => 'blog#content', as: :blog_content


  get '/html_export/:user_id/:project_id/' => 'excel#html_export', as: :html_export

  get '/templates/:path' => 'templates#template',
    :constraints => { :path => /.+/  }

  get '/hse' => 'hse#redirect', as: 'hse'

  post '/blog_images' => 'blog_images#create', as: :blog_images

  #get '*path' => redirect('/')
  root 'blog#index'
end

app/controllers/excel_controller.rb
class ExcelController < ApplicationController
  skip_before_filter :authenticate_user!
  layout :resolve_layout

  def daily_report
    @project    = Project.find(params[:project_id])
    @profession = Profession.find(params[:profession_id])
    @workers    = @project.users_with_profession(profession: @profession)
    @overtime   = params[:overtime]
    @filename   = DailyReport.new(project: @project, profession: @profession,
                                 overtime: @overtime).create_spreadsheet
    @hours_spent = @project.hours_spent_for_profession(@profession,
                                                       overtime: @overtime,
                                                       of_kind: :billable)
    @week_numbers = HoursSpent.week_numbers(@hours_spent)
    approve @project

    respond_to do |format|
      format.pdf do
        filename = generate_daily_report_pdf(project: @project,
                                             profession_title: @profession.title,
                                             overtime: @overtime)
        send_file filename, filename: File.basename(filename)
      end
      format.html do
        render 'daily_report-table'
      end
    end
  end

  def weekly_report
    @project    = Project.find(params[:project_id])
    @workers    = @project.users
    @overtime   = params[:overtime]
    @filename   = WeeklyReport.new(project: @project, profession: @profession,
                                   overtime: @overtime).create_spreadsheet
    respond_to do |format|
      format.pdf do
        filename = generate_daily_report_pdf(project: @project,
                                             profession_title: @profession.title,
                                             overtime: @overtime)
        send_file filename, filename: File.basename(filename)
      end
      format.html do
        @hours_spent = @project.hours_spent_for_profession(@profession,
                                                           overtime: @overtime)
        render 'daily_report-table'
      end
    end
  end

  def monthly_report
    if Date::MONTHNAMES[params[:month].to_i]
      @project =  Project.find(params[:project_id])
      @month =  params[:month]
      @year =  params[:year]
      overtime   = params[:overtime]
      @monthly_report, @total_weeks =  @project.generate_monthly_report(@year, @month, overtime)

      respond_to do |format|
        format.pdf do
          filename = generate_monthly_report_pdf(project: @project)
          send_file filename, filename: File.basename(filename)
        end
        format.html do
          render 'monthly_report'
        end
      end
    else
      redirect_to root_path, alert: "Please Enter a Valid Month Number."
    end
  end

  def timesheets
    @customers = Customer.all
  end


  # The timesheet is given to the customers HR department. It's used for
  # calucation sallery for the workers.
  # From and to date: Use the date from the first HoursSpent and the last.
  def timesheet
    @project = Project.find(params[:project_id])
    @user    = User.find(params[:user_id])
    @hours   = @project.hours_spents.where(user: @user).all
    filename = Timesheet.new(@project, @user,
                              @hours).create_spreadsheet
    send_file filename, filename:  filename
  end

  private

  def generate_daily_report_pdf(project:, profession_title:, overtime:)
    filename = "/tmp/daily_report-#{project.project_number.parameterize}-" +
               "#{project.address.parameterize}-" +
               "#{profession_title.parameterize}-#{overtime}"+
               "#{DateTime.now.strftime'%Y-%m-%d'}.pdf"
    url  = request.original_url.gsub('.pdf', '')
    kit  = PDFKit.new(url)
    kit.to_file(filename)
    filename
  end

  def generate_monthly_report_pdf(project:)
    filename = generate_filename(report_name: 'monthly_report', project: project)
    url  = request.original_url.gsub('.pdf', '')
    kit  = PDFKit.new(url)
    kit.to_file(filename)
    filename
  end

  def generate_filename(report_name:, project: project)
     "/tmp/monthly_report-#{p.project_number.parameterize}" +
     "-#{p.address.parameterize}-#{DateTime.now.strftime'%Y-%m-%d'}.pdf"
  end

  def offsett(nr)
    r = []
    nr.times do
      r << ''
    end
    r
  end

  def resolve_layout
    case action_name
    when 'daily_report', 'monthly_report'
      'excel'
    when 'timesheet'
      'excel'
    else
      'application'
    end
  end

end

app/helpers/excel_helper.rb
module ExcelHelper
  def fetch_date(month, year)
    "#{Date::MONTHNAMES[month.to_i]}, #{year}"
  end

  def extract_prf_dep(value)
    value.split('_').join('/')
  end
end

app/views/excel/dagsrapport-table.html.slim
- content_for :breadcrumb do
  = link_to 'Mine prosjekter', projects_path
  = fa_icon 'chevron-right'
  = link_to @project.name, customer_project_path(@project.customer, @project)
  = fa_icon 'chevron-right'
  strong= 'Dagsrapport'

= image_tag 'alliero-bratfoss-h46.png'

h3= "#{@profession.title.titleize} - #{t @overtime}"
br

.details
  div
    span.cell1
      strong År
    span.data_cell
      strong = " #{@project.created_at.year}"
    span.cell3
      strong Pågår
  br
  div
    span.cell1
      strong Uke
    span.data_cell
      strong = " #{@project.week_numbers}"
    span.cell3
      strong Ferdigstilt
  br
  div
    span.cell1
      strong Prosjektnummer
    span.data_cell
      strong= " #{@project.project_number}"
  br
  div
    span.cell1
      strong Kunde
    span.data_cell
      strong= " #{@project.customer.name}"
  br
  div
    span.cell1
      strong Adresse
    span.data_cell
      strong= " #{@project.address}"

.clearfix
table
  thead
    tr.gray_bg
      td Dato
      td Beskrivelse
      - @workers.each do |w| 
        td = w.name 
  tbody
    - @hours_spent.each_with_index do |hs,i|
      tr
        td= hs.created_at.strftime("%d/%m")
        td= hs.changed_value(:description) 
        - return_users_nr_in_array(@workers, user: hs.user).times do
          td= nbsp
        td= hs.changed_value(@overtime) 
        - add_remaining_tds(@workers, user: hs.user).times do
          td= nbsp 
    tr.gray_bg
      td.gray_bg(colspan='2')= "Sum #{t(@overtime).downcase} pr person"
      - @workers.each do |w|
        td.number= @project.hours_total_for(w, changed: true, overtime: @overtime)

      /- return_users_nr_in_array(@workers, user: hs.user).times do
      /  td
      /- add_remaining_tds(@workers, user: w).times do
      /  td  'h'


//  #nyrap
//    #header.bg_gray
//      .cell.date Dato
//      .cell.description Beskrivelse
//      - @workers.each do |w| 
//          .cell.name.vertical-textX = w.name 
//    #body
//      - @hours_spent.each_with_index do |hs,i|
//        .clearfix
//        .row
//          .cell.date=        hs.created_at.strftime("%d/%m")
//          .cell.description= hs.changed_value(:description) 
//          - return_users_nr_in_array(@workers, user: hs.user).times do
//            .cell= nbsp
//          .cell.overtime= hs.changed_value(@overtime) 
//    #sum
//      .cell.intro = "Sum #{t(@overtime).downcase} pr person"
//      - @workers.each do |w|
//        .cell.number= @project.hours_total_for(w, changed: true, overtime: @overtime)
//  
//  
//        //- return_users_nr_in_array(@workers, user: hs.user).times do
//        //  td
//        //td
//          = hs.changed_value(@overtime) 
//        /- add_remaining_tds(@workers, user: hs.user).times do
//          td

app/views/excel/dagsrapport.html.slim
- content_for :breadcrumb do
  = link_to 'Mine prosjekter', projects_path
  = fa_icon 'chevron-right'
  = link_to @project.name, customer_project_path(@project.customer, @project)
  = fa_icon 'chevron-right'
  strong= 'Dagsrapport'

= image_tag 'alliero-bratfoss-h46.png'

h3= "#{@profession.title.titleize} - #{t @overtime}"
br

.details
  div
    span.cell1
      strong År
    span.data_cell
      strong = " #{@project.created_at.year}"
    span.cell3
      strong Pågår

  br

  div
    span.cell1
      strong Uke
    span.data_cell
      strong = " #{@project.week_numbers}"
    span.cell3
      strong Ferdigstilt

  br
  div
    span.cell1
      strong Prosjektnummer
    span.data_cell
      strong= " #{@project.project_number}"


  br
  div
    span.cell1
      strong Kunde
    span.data_cell
      strong= " #{@project.customer.name}"

  br
  div
    span.cell1
      strong Adresse
    span.data_cell
      strong= " #{@project.address}"

.clearfix
#nyrap
  #header.bg_gray
    .cell.date Dato
    .cell.description Beskrivelse
    - @workers.each do |w| 
        .cell.name.vertical-text = w.name 
  #body
    - @hours_spent.each_with_index do |hs,i|
      .clearfix
      .row
        .cell.date=        hs.created_at.strftime("%d/%m")
        .cell.description= hs.changed_value(:description) 
        - return_users_nr_in_array(@workers, user: hs.user).times do
          .cell= nbsp
        .cell.overtime= hs.changed_value(@overtime) 
  #sum
    .cell.intro = "Sum #{t(@overtime).downcase} pr person"
    - @workers.each do |w|
      .cell.number= @project.hours_total_for(w, changed: true, overtime: @overtime)


      //- return_users_nr_in_array(@workers, user: hs.user).times do
      //  td
      //td
        = hs.changed_value(@overtime) 
      /- add_remaining_tds(@workers, user: hs.user).times do
        td


//table#dagsrapport
//  thead
//    th Dato
//    th Beskrivelse
//    - @workers.each do |w| 
//      th.vertical-text= w.name 
//  tbody
//    - @hours_spent.each_with_index do |hs,i|
//      tr
//        td= hs.created_at.strftime("%d/%m")
//        td= hs.changed_value(:description) 
//        - return_users_nr_in_array(@workers, user: hs.user).times do
//          td
//        td
//          = hs.changed_value(@overtime) 
//        - add_remaining_tds(@workers, user: hs.user).times do
//          td
//
//    - 5.times do
//      tr.spacer
//        - ((@workers.size) +2).times do
//          td= nbsp
//
//    tr.sum.bg_gray
//      td= "Sum #{t(@overtime).downcase} pr person"
//      td
//      - @workers.each do |w|
//        td= @project.hours_total_for(w, changed: true, overtime: @overtime)
//

br
br
br
br

app/views/excel/daily_report-table.html.slim
- content_for :breadcrumb do
  = link_to t('my_projects'), projects_path
  = fa_icon 'chevron-right'
  = link_to @project.name, customer_project_path(@project.customer, @project)
  = fa_icon 'chevron-right'
  strong= t('day_report')

= image_tag 'alliero-bratfoss-h46.png'

h3= "#{@profession.title.titleize} - #{t @overtime}"
br

.details
  div
    span.cell1
      strong= t('year')
    span.data_cell
      strong = " #{@project.start_date.year}"
    span.cell3
      strong= t('progress')
  br
  div
    span.cell1
      strong= t('week')
    span.data_cell
      strong = @week_numbers
    span.cell3
      strong= t('completed')
  br
  div
    span.cell1
      strong= t('project_number')
    span.data_cell
      strong= " #{@project.project_number}"
  br
  div
    span.cell1
      strong= t('customer')
    span.data_cell
      strong= " #{@project.customer.name}"
  br
  div
    span.cell1
      strong= t('address')
    span.data_cell
      strong= " #{@project.address}"

.clearfix
table
  thead
    tr.gray_bg
      td= t('date.date')
      td= t('description')
      - @workers.each do |w| 
        td = w.name 
  tbody
    - @hours_spent.each_with_index do |hs,i|
      tr
        td= hs.date.strftime("%d/%m")
        td= hs.description
        - return_users_nr_in_array(@workers, user: hs.user).times do
          td= nbsp
        td= hs.send(@overtime) 
        - add_remaining_tds(@workers, user: hs.user).times do
          td= nbsp 
    tr.gray_bg
      td.gray_bg(colspan='2')= "Sum #{t(@overtime).downcase} pr person"
      - @workers.each do |w|
        td.number= @project.hours_total_for(w, of_kind: :billable,
                    overtime: @overtime)

-if @overtime == 'runs_in_company_car'
  table
    thead
      tr.gray_bg
        td= t('date.date')
        td= t('supplies')
        td= t('name')
        td= t('text')
    tbody
      - @hours_spent.each do |hs|
        tr
          td= hs.date.strftime("%d/%m")
          td= hs.supplies_from_warehouse
          td= hs.user.name
          td= hs.description

app/views/excel/daily_report.html.slim
- content_for :breadcrumb do
  = link_to 'Mine prosjekter', projects_path
  = fa_icon 'chevron-right'
  = link_to @project.name, customer_project_path(@project.customer, @project)
  = fa_icon 'chevron-right'
  strong= 'Dagsrapport'

= image_tag 'alliero-bratfoss-h46.png'

h3= "#{@profession.title.titleize} - #{t @overtime}"
br

.details
  div
    span.cell1
      strong År
    span.data_cell
      strong = " #{@project.created_at.year}"
    span.cell3
      strong Pågår

  br

  div
    span.cell1
      strong Uke
    span.data_cell
      strong = " #{@project.week_numbers}"
    span.cell3
      strong Ferdigstilt

  br
  div
    span.cell1
      strong Prosjektnummer
    span.data_cell
      strong= " #{@project.project_number}"


  br
  div
    span.cell1
      strong Kunde
    span.data_cell
      strong= " #{@project.customer.name}"

  br
  div
    span.cell1
      strong Adresse
    span.data_cell
      strong= " #{@project.address}"

.clearfix
#nyrap
  #header.bg_gray
    .cell.date Dato
    .cell.description Beskrivelse
    - @workers.each do |w| 
        .cell.name.vertical-text = w.name 
  #body
    - @hours_spent.each_with_index do |hs,i|
      .clearfix
      .row
        .cell.date=        hs.created_at.strftime("%d/%m")
        .cell.description= hs.description) 
        - return_users_nr_in_array(@workers, user: hs.user).times do
          .cell= nbsp
        .cell.overtime= hs.send(@overtime) 
  #sum
    .cell.intro = "Sum #{t(@overtime).downcase} pr person"
    - @workers.each do |w|
      .cell.number= @project.hours_total_for(w, changed: true, overtime: @overtime)


      //- return_users_nr_in_array(@workers, user: hs.user).times do
      //  td
      //td
        = hs.send(@overtime) 
      /- add_remaining_tds(@workers, user: hs.user).times do
        td


//table#daily_report
//  thead
//    th Dato
//    th Beskrivelse
//    - @workers.each do |w| 
//      th.vertical-text= w.name 
//  tbody
//    - @hours_spent.each_with_index do |hs,i|
//      tr
//        td= hs.created_at.strftime("%d/%m")
//        td= hs.send(:description) 
//        - return_users_nr_in_array(@workers, user: hs.user).times do
//          td
//        td
//          = hs.send(@overtime) 
//        - add_remaining_tds(@workers, user: hs.user).times do
//          td
//
//    - 5.times do
//      tr.spacer
//        - ((@workers.size) +2).times do
//          td= nbsp
//
//    tr.sum.bg_gray
//      td= "Sum #{t(@overtime).downcase} pr person"
//      td
//      - @workers.each do |w|
//        td= @project.hours_total_for(w, changed: true, overtime: @overtime)
//

br
br
br
br

app/views/excel/export.html.slim
h1 Excel#export
p Find me in app/views/excel/export.html.slim

app/views/excel/html_export.html.slim
.outer-frame
  ul.l1c1
    li.span2 Alliero Gruppen
    li.span6 Gjerdrums vei 12 A, Postboks 4681 Nydalen, 0405 Oslo
    li.span1 &nbsp;
    li.span1 &nbsp;
    li.span1 &nbsp;
    li.logo

app/views/excel/monthly_report.html.slim
- date = fetch_date(@month, @year)
= image_tag 'alliero-bratfoss-h46.png'

h3= "Project:  #{@project.name.titleize}"
- if @monthly_report[@project.name][:sum] > 0
  table
    thead
      tr
        td colspan=2 Profession/Department
        td colspan=@total_weeks Week/Hour
        td colspan=1 = date
    tbody
      tr
        td colspan=2
        - @monthly_report[@project.name].each do |k,v|
          td.bold_data = (k == :sum) ? "Hours" :  k

      - @monthly_report.each do |key,value|
        tr
          td colspan=2 = @project.name == key ? "Sum" : extract_prf_dep(key)
          - value.each do |k,v|
            td = v
- else
  h5= "No Hours Spent For '#{date}'"

app/views/excel/timesheets.html.slim
h1 Timelister for inneværende måned
br
br

- @customers.each do |c|
  - next '' if c.projects.blank?
  - if c.projects.first.users.size
    h3= c.name
    br

    - c.projects.each do |p|
      - next '' unless p.users.present?
      = link_to project_number(p), p
      br
      - if p.users.present?
        ul.timesheets
          - p.users.each do |a|
            li
              = link_to "Last ned timeslisten til #{a.name}", 
                timesheet_path(p.id,a.id)

  hr